data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 4
    num_val_workers: 0 # Avoid a weird val dataloader issue
    train:
      target: ldm.data.simple.hf_dataset
      params:
        name: polytechXhf/jojos-dataset-small
        image_transforms:
          - target: torchvision.transforms.Resize
            params:
              size: 512
              interpolation: 3
          - target: torchvision.transforms.RandomCrop
            params:
              size: 512
          - target: torchvision.transforms.RandomHorizontalFlip
    validation:
      target: ldm.data.simple.TextOnly
      params:
        captions:
          - "A jojo's character with a helmet and a helmet on a tree"
          - "An cute dog eating his food"
          - "Dio Brando"
          - "anime - style image of a man in a white shirt and jeans"
        output_size: 512
        n_gpus: 2 # small hack to make sure we see all our samples
