DATASET_PATH = "./Dataset"
DATASET_IMAGE_EXTENSION = ".jpg"

JOJO_PAGE_LINK  = "https://jojo.fandom.com/"
JOJO_CHARS_LIST_LINK  = "https://jojo.fandom.com/wiki/Category:Characters"
JOJO_CHARACTER_CLASS  = "category-page__member-link"
JOJO_TARGET_CLASS  = "image image-thumbnail"
JOJO_CHAR_NAME_FILENAME = "JojosCharactersNames.txt"
JOJO_DATASET_PATH = "./Dataset/JojosDataset"
JOJO_IMAGE_NAME = "JojosImages"

ONEPIECE_PAGE_LINK  = ""
ONEPIECE_CHARS_LIST_LINK  = ""
ONEPIECE_CHARACTER_CLASS  = ""
ONEPIECE_TARGET_CLASS  = ""
ONEPIECE_CHAR_NAME_FILENAME = "OnePieceCharactersNames.txt"
ONEPIECE_DATASET_PATH = "./Dataset/OnePieceDataset"
ONEPIECE_IMAGE_NAME = "OnepiecesImages"